# Generated by Django 4.2.6 on 2023-10-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='derivdata',
            name='option',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='registrationoption',
            name='option',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='sensitiveinfo',
            name='option',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='socialreg',
            name='option',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='userage',
            name='target_users_under_18',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default=False, max_length=3),
        ),
    ]
