# Generated by Django 4.2.6 on 2023-10-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0005_alter_privacypolicyanswer_facebook_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishspellingoption',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infoapp',
            name='has_offer_wall',
            field=models.BooleanField(blank=True, null=True, verbose_name="Does your mobile app have an 'offer wall'?"),
        ),
        migrations.AlterField(
            model_name='infoapp',
            name='user_will_collect_device_info',
            field=models.BooleanField(blank=True, null=True, verbose_name="Will you be collecting any information regarding your users' mobile devices?"),
        ),
        migrations.AlterField(
            model_name='infoapp',
            name='user_will_request_features',
            field=models.BooleanField(blank=True, null=True, verbose_name="Will you be requesting access to features on your users' mobile devices?"),
        ),
        migrations.AlterField(
            model_name='infoapp',
            name='user_will_request_geolocation',
            field=models.BooleanField(blank=True, null=True, verbose_name="Will you be requesting access to your users' geolocations?"),
        ),
        migrations.AlterField(
            model_name='infoapp',
            name='user_will_send_push_notifications',
            field=models.BooleanField(blank=True, null=True, verbose_name='Will you be sending push notifications to your users?'),
        ),
        migrations.AlterField(
            model_name='personalinfooption',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='urlanswer',
            name='facebook_application',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook Application URL'),
        ),
        migrations.AlterField(
            model_name='urlanswer',
            name='mobile_application',
            field=models.URLField(blank=True, null=True, verbose_name='Mobile Application URL'),
        ),
        migrations.AlterField(
            model_name='urlanswer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website URL'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='Canada_users',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do you have users in Canada?'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='EU_users',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do you have users in the EU, UK, Switzerland, Iceland, Liechtenstein, or Norway?'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='US_users',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do you have users in the United States?'),
        ),
    ]
