# Generated by Django 4.2.6 on 2023-10-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0007_alter_derivdata_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoapp',
            name='has_offer_wall',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name="Does your mobile app have an 'offer wall'?"),
        ),
        migrations.AlterField(
            model_name='infoapp',
            name='user_will_collect_device_info',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name="Will you be collecting any information regarding your users' mobile devices?"),
        ),
        migrations.AlterField(
            model_name='infoapp',
            name='user_will_request_features',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name="Will you be requesting access to features on your users' mobile devices?"),
        ),
        migrations.AlterField(
            model_name='infoapp',
            name='user_will_request_geolocation',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name="Will you be requesting access to your users' geolocations?"),
        ),
        migrations.AlterField(
            model_name='infoapp',
            name='user_will_send_push_notifications',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Will you be sending push notifications to your users?'),
        ),
    ]
