# Generated by Django 4.2.6 on 2023-10-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0008_alter_infoapp_has_offer_wall_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocation',
            name='Canada_users',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Do you have users in Canada?'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='EU_users',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Do you have users in the EU, UK, Switzerland, Iceland, Liechtenstein, or Norway?'),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='US_users',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50, null=True, verbose_name='Do you have users in the United States?'),
        ),
    ]
